version: '3.8'

services:
  # O Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: physio_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: physio_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Este volume executa o script SQL automaticamente na primeira vez
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Interface visual para gerenciar o banco (acesso via navegador)
  pgadmin:
    image: dpage/pgadmin4
    container_name: physio_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: